### ISSUE TITLE
auro-hyperlink: Feature Request - 'fluid' attribute for CTA buttons

### ISSUE THREAD

**Issue by MattSidor** [AlaskaAirlines/auro-hyperlink#137]
## Is your feature request related to a problem? Please describe.

`<auro-button>` has a `fluid` attribute ([docs](https://auro.alaskaair.com/components/auro/button#fluid&gsc.tab=0)) which alters the width of the button to fill the full width of its parent container. The CTA button variant of `<auro-hyperlink>` does not currently support this.

## Describe the solution you'd like

I would like the CTA buttons to support a `fluid` attribute, just like `<auro-button>`.

## Describe alternatives you've considered

We considered using `<auro-button>` instead, but it would not be appropriate or accessible since we are linking out to a different URL.

## Additional context

[This is the Figma we are trying to implement.](https://www.figma.com/file/6BDLuqazwYXRq1x241SYN7/Same-Day-Confirmed-(SDC)?node-id=3926%3A73614&t=TMBECltHA1mXjPBX-0) (Screenshot also posted below.) The "Continue to check in" CTA button at the bottom would link to the check-in page. ([AB#756550](https://dev.azure.com/itsals/E_Serve_Manage/_boards/board/t/E_Serve_Manage%20Team/Stories/?workitem=756550))

<img width="386" alt="Screen Shot 2022-11-23 at 12 31 46 PM" src="https://user-images.githubusercontent.com/6138182/203640952-89576931-f231-40e2-8cbd-1ba4ffc90f96.png">

**Comment by blackfalcon** [comment]
@leeejune please reach out to the designer of this UI. There is an incorrect assumption of use with the Button UI over a hyperlink. 

The use case here is that the designer wanted to use a Button UI, but this action is actually a hyperlink to a new page. @MattSidor reached out for updates to the CTA version of the hyperlink, but we need to review/discuss what that means.
