### ISSUE TITLE
As a developer I need help with building js in windows machines

### ISSUE THREAD

**Issue by Izook** [AlaskaAirlines/auro-hyperlink#153]
# General Support Request

## Support request

Update the `copfiles` command in the `dist:js` script to use double quotes instead of single quotes to allow for window machine support. 

[Source](https://github.com/calvinmetcalf/copyfiles/blob/master/readme.md?plain=1#L30)

## Possible Solution

```diff
+    "dist:js": "copyfiles -u 1 -V \"./src/**/*.js\" ./dist",
-   "dist:js": "copyfiles -u 1 -V './src/**/*.js' ./dist",
```

## Context

Hoping to provide more support for windows users. 

## Your Environment

* Version used: 3.2.2
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): Windows 
* Link to your project: N/A

**Comment by blackfalcon** [comment]
This code is actually being removed from auro-hyperlink in an upcoming release. 

- https://github.com/AlaskaAirlines/auro-hyperlink/pull/154/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
