### ISSUE TITLE
Small cta buttons

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-hyperlink#172]
## Is your feature request related to a problem? Please describe.

Some of our marketing placements are small and have a need for a CTA that is much smaller than the standard CTA.

![image](https://github.com/AlaskaAirlines/auro-hyperlink/assets/5118118/e33df863-3bf3-44ff-8179-00f1414fa5ae)

## Describe the solution you'd like

Basically the same thing that was implemented on `<auro-button slim>` but for `<auro-hyperlink type="cta">`  We'll also need to update the figma component updated to match this and have the exact specs before we implement this feature.

## Describe alternatives you've considered

Using the standard link type is the alternative and that works for the really small placements.

## Additional context

Currently when designers create this, the web content team has to recreate the hyperlink component with CSS.  This feature would eliminate the need to do that.  This would also allow slim buttons and slim hyperlinks to live next to each other.

## Verify the version of @aurodesignsystem/auro-hyperlink you have installed

**The current version is:**
[![See it on NPM!](https://img.shields.io/npm/v/@aurodesignsystem/auro-hyperlink?style=for-the-badge&color=orange)](https://www.npmjs.com/package/@aurodesignsystem/auro-hyperlink)

My project has @aurodesignsystem/auro-hyperlink v installed

Need design blueprint for using auro-hyperlink as a "slim cta" that is the same size as `auro-button` so that designers can use the two interchangeable.

**Comment by yvonneyamasaki** [comment]
Here is the Blueprint for the smaller Hyperlink CTA

https://www.figma.com/file/TSFOFDwWQxmpPpYQ2F06lH/Hyperlink?type=design&node-id=2233-2573&mode=design

<img width="407" alt="Screenshot 2023-11-01 at 11 25 04 AM" src="https://github.com/AlaskaAirlines/auro-hyperlink/assets/144830559/ae0dafde-9882-4674-b13a-7d76805541fd">
<img width="358" alt="Screenshot 2023-11-01 at 11 25 16 AM" src="https://github.com/AlaskaAirlines/auro-hyperlink/assets/144830559/5943ed0f-b574-4df4-bf11-d632f7cae4bf">
<img width="579" alt="Screenshot 2023-11-01 at 11 25 23 AM" src="https://github.com/AlaskaAirlines/auro-hyperlink/assets/144830559/1fc2b015-6074-45a5-b9cf-584d32b5abe6">
