### ISSUE TITLE
introduce `span` with css part around slot when no href is present

### ISSUE THREAD

**Issue by Izook** [AlaskaAirlines/auro-hyperlink#175]
## Is your feature request related to a problem? Please describe.

- when customizing hyperlinks it is difficult to get consistent styling between cases when the `href` is and isn't present

## Describe the solution you'd like

- provide a span when `href` isn't present to provide something to style

## Describe alternatives you've considered

- overriding the render function of hyperlink to add a span around the slotted content when the hyperlink isnt present

## Verify the version of @aurodesignsystem/auro-hyperlink you have installed

**The current version is:**
[![See it on NPM!](https://img.shields.io/npm/v/@aurodesignsystem/auro-hyperlink?style=for-the-badge&color=orange)](https://www.npmjs.com/package/@aurodesignsystem/auro-hyperlink)

My project has @aurodesignsystem/auro-hyperlink v3.3.3 installed

**Comment by blackfalcon** [comment]
The styling of a hyperlink NOT looking like a link when the href is not present is intentional. Adding a CSS part to override this would negate the deliberate feature of the component.
