### ISSUE TITLE
auro-hyperlink: hover color and implementation match auro-button

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-hyperlink#189]
### Is your feature request related to a problem? Please describe.

We are updating the hover color of `auro-button` and we need `auro-hyperlink` to match so that the hover experiences of both components are identical.

### Describe the solution you'd like

Use the background-image: linear-gradient solution that was implemented on auro-button

### Describe alternatives you've considered

Remain inconsistent

### Additional context

This is part of the larger goal of standardizing auro-button and auro-hyperlink.  This is the related commit in the auro-button PR https://github.com/AlaskaAirlines/auro-button/pull/228/commits/918f5630dec1a6815921ad9b9e963d2f6d830dd4

### Exit criteria

When the hover experience matches auro-button's hover experience. https://github.com/AlaskaAirlines/auro-button/issues/227

**Comment by blackfalcon** [comment]
**RECOMMENDATION**: This UI should be redone as a Auro Design Token with a semantic name to be used between the CTA and auro-button allowing for easy consistency and easy theming. 

See https://github.com/AlaskaAirlines/AuroDesignTokens/commit/f6e99a4f4806b83175e31e3c8d0f16cc33b85b7e for recently added gradient token.
