### ISSUE TITLE
auro-hyperlink: semantic theming for sizing

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-hyperlink#196]
This issue is related to this issue https://github.com/AlaskaAirlines/auro-button/issues/243
#### Needs a tier 2 token
https://github.com/AlaskaAirlines/auro-hyperlink/blob/ede1d3f70e955fb8e714f216ddabd81865a79fc1/src/style.scss#L120
https://github.com/AlaskaAirlines/auro-hyperlink/blob/ede1d3f70e955fb8e714f216ddabd81865a79fc1/src/style.scss#L121
https://github.com/AlaskaAirlines/auro-hyperlink/blob/ede1d3f70e955fb8e714f216ddabd81865a79fc1/src/style.scss#L152
https://github.com/AlaskaAirlines/auro-hyperlink/blob/ede1d3f70e955fb8e714f216ddabd81865a79fc1/src/style.scss#L229
https://github.com/AlaskaAirlines/auro-hyperlink/blob/ede1d3f70e955fb8e714f216ddabd81865a79fc1/src/style.scss#L73
https://github.com/AlaskaAirlines/auro-hyperlink/blob/ede1d3f70e955fb8e714f216ddabd81865a79fc1/src/style.scss#L243
https://github.com/AlaskaAirlines/auro-hyperlink/blob/ede1d3f70e955fb8e714f216ddabd81865a79fc1/src/style.scss#L246
https://github.com/AlaskaAirlines/auro-hyperlink/blob/ede1d3f70e955fb8e714f216ddabd81865a79fc1/src/style.scss#L247

#### Should use a new tier 2 token.  Currently the token describes the value since it references "Darkest" or "Lightest" 
https://github.com/AlaskaAirlines/auro-hyperlink/blob/ede1d3f70e955fb8e714f216ddabd81865a79fc1/src/style.scss#L164

### Exit criteria

- [ ] All SASS references have been updated to CSS variables
- [ ] There are no longer tier 1 tokens referenced in this repo.
- [ ] All lines listed have been addressed.
- [ ] All CTA states have tokens.  (visited, hover, focus, focus-visible, active, etc.)

**Comment by blackfalcon** [comment]
@leeejune is there any suggestions you can offer here to address this work? While this is an update to the hyperlink element, the pre-work for creating these requested tokens is not defined anywhere. 

Please advise and a new Tokens issue will need to be created defining that work.

**Comment by blackfalcon** [comment]
@leeejune @jason-capsule42 @jordanjones243 this issue is pretty old. Can anyone offer any insight as to if this work still needs to be done? 

I am reassigning this to triage for team review.
