### ISSUE TITLE
Wayward bullets 

### ISSUE THREAD

**Issue by vhenderson12** [AlaskaAirlines/auro-hyperlink#208]
### Please describe the bug

1. Go to "travel advisories" page 
2. View on mobile or view mobile sizing in browser
3. The problem is in the list view that breaks into two lines

<img width="369" alt="Screenshot 2024-06-18 at 1 40 33 PM" src="https://github.com/AlaskaAirlines/auro-nav/assets/173202829/e7b44c22-3745-4ca6-ab9c-3cbf30e084a7">

### Reproducing the error

None

### Expected behavior

We expect to see the bullet at the top of the list item content instead of at the bottom. 

### What browsers are you seeing the problem on?

Chrome, Safari

### Exit criteria

We need a bulleted list of hyperlink with the bullets in the correct spot at the top of each list item when the hyperlinks break across multiple lines.

**Comment by blackfalcon** [comment]
@vhenderson12 can you verify what version of auro-hyperlink you have installed in your app? After some review, we have released updates in the past that addressed this situation, but I do not see the code in the reference URL listed.

**Comment by blackfalcon** [comment]
Setting status to BLOCKED until we have verification on the version of the element used in this UI.

**Comment by jordanjones243** [comment]
After some digging, @jason-capsule42 and I uncovered that this is not an Auro bug and we will be closing this ticket. We have found a solution that we tested on the live travel advisories site by inserting this code in a `<style>` element and placing that into the `<head>` of the document:

`li > * {
    vertical-align: text-top;
}`

Please see this link for reference of this fix: https://jsfiddle.net/2ma994cr/1/

@vhenderson12
