### ISSUE TITLE
Design: auro-hyperlink CTA support 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-hyperlink#22]
## Is your feature request related to a problem? Please describe.

There are multiple use cases in which there is the need for a CTA button to draw a user's attention. 

We need a designed CTA solution that is distinctive from the main auro-button and is coded as a hyperlink as this is a link to a web page, file, email address, location on the same page, or anything else a URL can address. 

## Describe the solution you'd like

A new design element that addresses this need and is distinctive from the standard auro-button.

The CTA will be implemented with the hyperlink component as a role state of button. 

There also needs to be a solution for inheriting the current styles from the auro-button

## Describe alternatives you've considered

None

## Additional context

None

## Exit criteria 

This story will be considered complete when the following is addressed:
- [x] discovery
- [x] design
- [x] stress-test
- [x] a fully documented design spec has been created 
- [x] the assets have been symbolized in the UI toolkit
- [x] the new UI has been applied to the WC
- [x] documentation has been accepted as a new standard for all future work to be measured against

A full review with Auro team members is required prior to closing this issue.

## Parent issue

https://github.com/AlaskaAirlines/auro_docs/issues/60

## Audit

https://github.com/AlaskaAirlines/auro_docs/issues/113

**Comment by blackfalcon** [comment]
Dev story https://github.com/AlaskaAirlines/ods-hyperlink/issues/27

**Comment by blackfalcon** [comment]
When searching the Abstract lib I am finding two different references to CTA. 

https://app.abstract.com/projects/2275e59a-5504-4c7d-b14d-52881b0a6db3/branches/master/files/528FCEE1-62FC-47B0-BFEF-D4511E580892/pages/57591AB8-5106-49E6-AE45-8C603A5D3D49

and 

https://app.abstract.com/projects/3b79fe3f-3a67-4df4-a60c-1d1174583a94/branches/master/files/ef124e0c-59b2-4cc6-bad1-1225772bbfaa

I am assuming the 2nd one is what we want to move forward on, but why is this in a different file set?

**Comment by blackfalcon** [comment]
@vidalmenAS can you please respond to the questions above?

**Comment by geoffrich** [comment]
@blackfalcon can this issue be closed now?
