### ISSUE TITLE
Non-compliant ESM code references

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-hyperlink#233]
### Please verify the version of auro-hyperlink you have installed

@latest

### Please describe the bug

See the following code

https://github.com/AlaskaAirlines/auro-hyperlink/blob/aa55e96585a323fdd7db1d7070824f036ae4b768/src/auro-hyperlink.js#L15

Import endpoint does not have syntax prefix causing consumer's build to break. 

### Reproducing the error on the docsite

This issue cannot be reproduced on the Auro docsite

### Expected behavior

Updated components should not break build pipelines. 

### What browsers are you seeing the problem on?

n/a

### Additional context

n/a

### Exit criteria

This issue can be closed once the incomplete code has been updated.

**Comment by jason-capsule42** [comment]
This was already fixed before this bug was opened as part of this work: https://github.com/AlaskaAirlines/auro-hyperlink/issues/231
