### ISSUE TITLE
auro-hyperlink: internal link, new window variant

### ISSUE THREAD

**Issue by clockeby** [AlaskaAirlines/auro-hyperlink#44]
## Is your feature request related to a problem? Please describe.
The icon and tooltip message added to auro-hyperlink when `target="_blank"` is included only addresses instances where the link directs guests to an external site which opens in a new tab/window. This is misleading when used for content which is located on alaskaair.com but also opens in a new tab/window. For example, within the booking path as a link to additional information without taking guests out of the booking process. 

## Describe the solution you'd like
One solution could be to vary the tooltip message (ie. This content will open in a new window) based on whether the href is an alaskaair.com address with `target="_blank"` or a link to an external site. A possible drawback to this solution is the icon would remain the same and possibly cause confusion if the tooltip message is not seen as well.

Expanding on this, a different icon could also be included for use with alaskaair.com link addresses which would better align with the new tab/window message. Some icons I have seen used for this are below.

![image](https://user-images.githubusercontent.com/9092702/106317321-04de7f80-6223-11eb-9a3e-4905723ba3a5.png)
![image](https://user-images.githubusercontent.com/9092702/106314972-600e7300-621f-11eb-8d1d-eb980259e07e.png)
![image](https://user-images.githubusercontent.com/9092702/106315043-80d6c880-621f-11eb-9bdb-1d95745e1927.png)
A possible drawback to this is at such a small size (current external site icon is 9px x 9px) one icon may not be easily distinguishable from the other and only add more visual clutter.

## Describe alternatives you've considered
Alternatively, we could remove the icon for links with an alaskaair.com address which include `target="_blank"` so they are displayed the same as other internal links. The drawback to this is there would be no notification that the content will open a new tab/window and could cause guests to assume they had been taken out of the booking path or other part of the site if they don't notice the new tab/window open.

## Additional context
I'd appreciate additional input on this. Do these details matter? Is combining the two a better approach than keeping consistent & independant contexts for each link instance?

**Comment by clockeby** [comment]
Ooops. I always forget to change the title on these. Should be "auro-hyperlink: internal link, new window variant"

**Comment by blackfalcon** [comment]
@clockeby this issue is spot on. I 100% agree as this issue has been raised with the Auro Icons lib. https://github.com/AlaskaAirlines/Icons/issues/34

If the solution is to offer an alternative API for the hyperlink component to allow for this choice, I can get behind that. 

Things I need: 

1. A new icon for this purpose
2. A description of this icon for a11y
3. An updated comp for the auro-hyperlink with this new icon

The new icon will be added to the Auro Icons lib and then auro-hyperlink can be updated with the new icon.

**Comment by clockeby** [comment]
@blackfalcon I think offering an alternative API for this option in the hyperlink component is a solid choice. I'll check with UI design on the icon direction & Asher for the description.

**Comment by blackfalcon** [comment]
This issue will remain in the backlog pending design direction.

**Comment by blackfalcon** [comment]
@clockeby is there any movement on this? Are there any plans to help move this forward?

**Comment by clockeby** [comment]
@blackfalcon YES! There's been some progress. I've created an icon based on initial feedback from the design team and have placeholder language for alt/tooltip text. I still need to get both approved by design and ux writing. I should have more info from them next week!

**Comment by blackfalcon** [comment]
The scope of this issue should also include getting a larger-sized icon for the CTA button options.

**Comment by clockeby** [comment]
The new icon will be an SVG created to the same specs as everything in the Auro icon library. It'll have all the sizes. :)

**Comment by clockeby** [comment]
@blackfalcon quick double check:

> Things I need:
~~A new icon for this purpose~~
~~A description of this icon for a11y~~
An updated comp for the auro-hyperlink with this new icon
The new icon will be added to the Auro Icons lib and then auro-hyperlink can be updated with the new icon.

I've created the new icon based on feedback from the UI team. Asher provided the a11y description to use in the `title` section of icons.json. I've submitted a pull request to review those changes. For the comp, do you just need a mockup showing the icon used with the link and button variants? Let me know & I'll add it since I finally have time to wrap this up.

**Comment by blackfalcon** [comment]
A couple of things. 

I am not sure the SVG is cut correctly. I think it's missing the space around the icon. See the screenshot below. The icon should not be hugging the upper-left like that. 

<img width="335" alt="Screen Shot 2021-03-16 at 1 22 33 PM" src="https://user-images.githubusercontent.com/181089/111374818-cb3ec800-865a-11eb-8dbd-d74c5df8656a.png">

As a follow-up, regarding auro-hyperlink, the current feature is when a dev uses `target="blank"` the assumption is that the link will not only open a new tab, but also be an external link. 

So for the update, this opinion will hold true, but we can add a new property like `internal` maybe? Then that would be the trigger to use the new icon.

**Comment by blackfalcon** [comment]
Closing. Moving work to https://github.com/AlaskaAirlines/auro-hyperlink/issues/52
