### ISSUE TITLE
Relative button without margin

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-hyperlink#49]
## Is your feature request related to a problem? Please describe.
Currently auro-hyperlink role="button" applies margin as it is using an anchorButton mixin. 
https://github.com/AlaskaAirlines/auro-hyperlink/blob/16ddbb4664fff886d67f47c2edd21637c167bb5f/src/style.scss#L66

## Describe the solution you'd like
A way to set role="button" without the margin.

Before:
![image](https://user-images.githubusercontent.com/7005799/110059095-6ad58f80-7d18-11eb-9aff-2e2c09a74686.png)
After:
![image](https://user-images.githubusercontent.com/7005799/110059128-7cb73280-7d18-11eb-9c68-0a5a1303215e.png)

Use Case:
Current:
![image](https://user-images.githubusercontent.com/7005799/110059157-86409a80-7d18-11eb-8e02-931662938e24.png)
Desired:
![image](https://user-images.githubusercontent.com/7005799/110059169-8e003f00-7d18-11eb-9311-a84bd36d8662.png)

## Describe alternatives you've considered
An additional prop for 'unformatted' like auro-interruption is desirable as we would not break any existing placements of role="button"

**Comment by blackfalcon** [comment]
I can't change the `role=button` feature without releasing a breaking change, and that doesn't seem worth it. 

What I can do is add a feature like `lowProfile` that gets you what you want. 

Thoughts?

**Comment by gusnaughton** [comment]
lowProfile works perfect! would you like me to pick up that work?

**Comment by blackfalcon** [comment]
@gusnaughton can you make this update or do you want us to take it on?

**Comment by blackfalcon** [comment]
@gusnaughton is this still needed?

**Comment by blackfalcon** [comment]
It's been over two months since this had any activity, so I am not seeing any reason to consider this work.
