### ISSUE TITLE
auro-hyperlink: missing focus styles when inside another shadow root

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-hyperlink#55]
## Describe the bug
When auro-hyperlink is rendered in another shadow root, focus styles do not apply.

Related: https://github.com/AlaskaAirlines/auro-button/issues/97

## To Reproduce
1. Create a component that renders auro-hyperlink in the shadow DOM
2. Attempt to tab to it. Notice that focus styles are not applied

## Expected behavior
Focus styles are applied.

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Firefox 
 - Version: 87

## Additional context
Fix should be similar to https://github.com/AlaskaAirlines/auro-button/pull/102

**Comment by blackfalcon** [comment]
This update should be addressed with https://github.com/AlaskaAirlines/auro-hyperlink/issues/39

**Comment by geoffrich** [comment]
This was not resolved with the linked PR. Since auro-hyperlink is often embedded in the component hangar components, I think it's worth applying the polyfill the same way auro-button does until we decided on the polyfill support going forward.

Reference: https://github.com/AlaskaAirlines/auro-button/pull/118
