### ISSUE TITLE
auro-hyperlink: nonPropagation of click event on hyperlink

### ISSUE THREAD

**Issue by Dayna-A** [AlaskaAirlines/auro-hyperlink#63]
## Is your feature request related to a problem? Please describe.

When an auro-hyperlink is nested in an auro-checkbox, clicking on the hyperlink causes the checkbox to be toggled.

## Describe the solution you'd like

Clicking on any other text inside of the checkbox slot should toggle the checkbox but not clicking on the hyperlink.

## Describe alternatives you've considered

We are catching the events and overriding event propagation but feel like [stopping events from propagating](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) outside of an auro-hyperlink might be a good thing to have baked in.

## Additional context

![image](https://user-images.githubusercontent.com/35708093/121444703-398ae200-c94d-11eb-98c2-7f52637bfdf3.png)
Click on stepout link
New tab opens & checkbox updates to this:
![image](https://user-images.githubusercontent.com/35708093/121444783-57584700-c94d-11eb-89ea-1d6efce9b4c7.png)

Related to Issue: https://github.com/AlaskaAirlines/auro-checkbox/issues/25

**Comment by blackfalcon** [comment]
The issue we are addressing here is that the `<label>` element is tethered to the `<input>` element for reasons of accessibility. This cannot change. 

The current architecture of the auro-input custom element is that there is a generic `<slot>` where a user can enter text that will appear in the `<label>` element. 

```html
<auro-checkbox id="unchecked" name="exampleOption" value="example checked option">Checkbox option</auro-checkbox>
```

A way out of this is to have a `<slot>` for the `<label>` and a slot for general content. This would also mean a slight change in how the structure of the content works. E.g., not having all the links within the same content as the primary label. 

Who is a design sponsor for this work?

**Comment by rallyb13** [comment]
> Who is a design sponsor for this work?

Kaitlin Reiss is the designer for NFP.

**Comment by blackfalcon** [comment]
There is a way to address this UI without having to reshape the auro-checkbox element. 

```html
<auro-checkbox id="computers" name="checkboxDemo6" value="computers" style="display: inline-block; margin-right: -5px">
  I understand this is a non-refundable purchase and agree</auro-checkbox>
  to the Alaska Lounge
  <auro-hyperlink href="/" target="_blank">
    terms and conditions
  </auro-hyperlink>
```

I feel that this is an acceptable approach to the problem without having to build in special case support into a primitive element.

**Comment by Dayna-A** [comment]
@rallyb13 you down?

**Comment by blackfalcon** [comment]
Here is my long-vision opinion on this. 

We should NOT be using this visual pattern due to issues with a11y. What we SHOULD be doing is embracing the newer modal of acceptance that are currently using with our Cookie Policy banner. 

<img width="1792" alt="Screen Shot 2021-06-14 at 10 53 01 AM" src="https://user-images.githubusercontent.com/181089/121936743-cd1e3300-ccfe-11eb-948d-9ac1503008a2.png">

This issue and the duplicate https://github.com/AlaskaAirlines/auro-checkbox/issues/25 will be closed as there are no proposed updates to be done with this or the auro-hyperlink primitive elements.

**Comment by Dayna-A** [comment]
@sk8lin?

**Comment by MattSidor** [comment]
Cross-posting from duplicate https://github.com/AlaskaAirlines/auro-checkbox/issues/25: Just for future reference, a possible workaround to this is to use the `onInput` event instead of `onClick`. The hyperlinks do not seem to trigger the checkbox when I use that event.
