### ISSUE TITLE
auro-hyperlink: unit test coverage

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-hyperlink#65]
## Is your feature request related to a problem? Please describe.
auro-hyperlink does not have good test coverage. It also uses a Polymer test setup that is different from the tests on the other Auro elements. This makes it difficult for devs to write tests when adding new features.

## Describe the solution you'd like
Add a new test setup using `@web/test-runner`. See the generator template for the current setup.

Add unit tests so that coverage is over 80%.

## Describe alternatives you've considered
n/a

## Additional context
n/a

**Comment by blackfalcon** [comment]
Work issue already created to address the massive upgrade of this older element. 
https://github.com/AlaskaAirlines/auro-hyperlink/issues/39
