### ISSUE TITLE
auro-hyperlink: cta button larger than auro-button

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-hyperlink#70]
## Describe the bug
I need an auro-hyperlink to take a guest out to a link, and an auro-button to fire a modal:
![image](https://user-images.githubusercontent.com/7005799/128802985-b5bec919-c1fa-4f1c-a4d8-dfe978896fd6.png)

It appears that by default, the cta button size is larger than the button. Is it possible to adjust the size of this element to be consistent, or is this the intended design?

## Expected behavior
auro-hyperlink button does not appear larger than a button

**Comment by blackfalcon** [comment]
You should not be using a 'button' look in that case. The point of the CTA is a Call To Action, not simply a hyperlink. 

Please talk with your designer as the proper thing to use is auro-hyperlink without the CTA UI.
