### ISSUE TITLE
Create blueprint figma file

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-hyperlink#77]
# General Support Request
Create a blueprint for hyperlink and all the variants.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by leeejune** [comment]
Got it! Please let me know if I should make edits after you edit the specs!

**Comment by blackfalcon** [comment]
This is not correct

<img width="856" alt="Screen Shot 2021-11-01 at 8 04 17 PM" src="https://user-images.githubusercontent.com/181089/139780892-3b915332-e86a-496a-b944-0b612b0930e0.png">

This is a hacked example from the doc site

<img width="506" alt="Screen Shot 2021-11-01 at 8 10 22 PM" src="https://user-images.githubusercontent.com/181089/139780871-e9ba31b5-c9b9-4af7-a4e0-6129ef44e48b.png">

**Comment by blackfalcon** [comment]
Tertiary CTA is not supported, should not be in the Figma doc

<img width="810" alt="Screen Shot 2021-11-01 at 8 11 59 PM" src="https://user-images.githubusercontent.com/181089/139780994-e299d7aa-e6d2-4b7c-b73e-6a9f0b8dc82f.png">

**Comment by blackfalcon** [comment]
@leeejune please see two previous comments.

**Comment by leeejune** [comment]
Got it! Edits made to blueprint:
- Removed teritary style from CTA button type
- Added correct focus state and edited hover state for Nav type

**Comment by blackfalcon** [comment]
@leeejune this looks good. Let's get the PR going for the Design .md file with the Figma frame and release notes.

**Comment by leeejune** [comment]
Will do! It is confirmed to publish on Figma as well?
