### ISSUE TITLE
A11Y and the underline

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-hyperlink#83]
@leeejune work with Erika on the hyperlink blueprint - figma ui toolkit so we have the lateset information.

Sounds like what we ultimately need is a new style that has no padding when we need "role=button" but we also want it styled like an inline hyperlink with an underline.

**Comment by leeejune** [comment]
We actually already have this available in the current Figma library. Here is a screenshot!
![Screen Shot 2021-11-23 at 7 25 04 AM](https://user-images.githubusercontent.com/55998746/142944184-d9f8d390-d8cf-43a8-b389-cf060d6c4b1c.png)

**Comment by braven112** [comment]
Let's use #82 for any further feedback and I'll close this issue.
