### ISSUE TITLE
Ability to pass referer information

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-hyperlink#84]
## Is your feature request related to a problem? Please describe.
The auro-hyperlink does not allow the referer attribute to be sent.  

## Describe the solution you'd like
What would be nice is to have the ability to send the referer domain and path when a user clicks on certain links.  This would be an opt in feature but could help with tracking.  This would enable teams to be able to tailor their experience based off of where the user came from.

## Describe alternatives you've considered
The alternative is to not use auro-hyperlink, when this is needed so they have the option to send this type of information.

## Additional context
This story is on the content teams backlog.  This page has additional details...
https://dev.azure.com/itsals/E_Retain_Content/_backlogs/backlog/E_Retain_Content%20Team/Stories/?workitem=645265

This is a request to be able to send the page referer information to a 3rd party website that they could use for analytics.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer

Security would be a concern as well
https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns

**Comment by blackfalcon** [comment]
What we are talking about here is supporting a scenario where when `_blank` is used in conjunction with the `referrerpolicy` attribute, there is a scenario where users can manage their referral policies. 

We can use the `referrerpolicy` attribute as a trigger to allow for opt in support and set the `rel` to `external` and remove the `noreferrer` default scenario.

### Note

While researching, the following was discovered. It is recommended that we not change support for adding this value to the `rel` attribute at this time as this support is realitivelly new. 

> As of Chromium version 88, anchors with target="_blank" automatically get noopener behavior by default. Explicit specification of rel="noopener" helps protect users of legacy browsers including Edge Legacy and Internet Explorer.
