### ISSUE TITLE
auro-hyperlink: minor docs error

### ISSUE THREAD

**Issue by who0** [AlaskaAirlines/auro-hyperlink#85]
## Describe the bug
There is a minor spelling bug in the docs. `noreferre` instead of `noreferrer`.

## To Reproduce
1. Go to https://github.com/AlaskaAirlines/auro-hyperlink/blob/master/docs/auro-api.md

**Comment by blackfalcon** [comment]
Update is already in progress with this draft PR to upgrade auro-hyperlink to the latest generator build and node 16 support. https://github.com/AlaskaAirlines/auro-hyperlink/pull/81/files#diff-19dd03f9924cd10251af2a8b2c1194324aabe9a8ff09a532ba1b81bd49ca4d3c
