### ISSUE TITLE
Design guidelines (do's and don'ts)

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-hyperlink#86]
# General Support Request
Design guidelines for hyperlink will be added to the Figma blueprint file. 

[Link](https://www.figma.com/file/TSFOFDwWQxmpPpYQ2F06lH/Hyperlink?node-id=0%3A810)

**Comment by blackfalcon** [comment]
Great progress. Looking awesome!

**Comment by leeejune** [comment]
Added all guidelines.

**Comment by blackfalcon** [comment]
So great! Good job!
